staging_transactions_table_drop_sql = "DROP TABLE IF EXISTS staging_transactions"
merchants_table_drop_sql = "DROP TABLE IF EXISTS merchants"
customers_table_drop_sql = "DROP TABLE IF EXISTS customers"
world_bank_stats_table_drop_sql = "DROP TABLE IF EXISTS world_bank_stats"

CREATE_STAGING_TRANSACTIONS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS staging_transactions (
staging_transactions_key INTEGER IDENTITY(0,1),
step                    INTEGER,            
transaction_type         VARCHAR(MAX) distkey,
transaction_amount      DOUBLE PRECISION,
originator_name         VARCHAR(MAX),
originator_old_balance  DOUBLE PRECISION,
originator_new_balance  DOUBLE PRECISION,
recepient_name          VARCHAR(MAX),
recepient_old_balance   DOUBLE PRECISION,
recepient_new_balance   DOUBLE PRECISION,
isFraud                 INTEGER,
isFlaggedFraud          INTEGER
);
"""

CREATE_MERCHANTS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS merchants (
merchant_key                 INTEGER IDENTITY(0,1),
merchant_name                VARCHAR(MAX),
cash_in_count                INTEGER,
cash_out_count               INTEGER,
payment_count                INTEGER,
distinct_customers_count     INTEGER
);
"""

CREATE_CUSTOMERS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS customers (
customer_key                               INTEGER IDENTITY(0,1),
customer_name                              VARCHAR(MAX),
cash_in_count                              INTEGER,
cash_out_count                             INTEGER,
payment_count                              INTEGER,
transfer_count                             INTEGER,
first_transaction_step_time                INTEGER,
last_transaction_step_time                 INTEGER,
distinct_top_transfer_to_customer_count    INTEGER,
distinct_merchant_count				       INTEGER
);
"""

CREATE_WORLD_BANK_STATS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS world_bank_stats (
stat_key                 INTEGER IDENTITY(0,1),
year         			 INTEGER,
country_code			 VARCHAR(MAX),
country_name			 VARCHAR(MAX),
region                   VARCHAR(MAX),
economic_status			 VARCHAR(MAX),
Account_age_15_plus 	 VARCHAR(MAX),
Account_male_age_15_plus	                                        VARCHAR(MAX),
Account_in_labor_force_age_15_plus 		                            VARCHAR(MAX),
Account_out_of_labor_force_age_15_plus 	                            VARCHAR(MAX),
Account_female_age_15_plus										    VARCHAR(MAX),
Account_young_adults_ages_15_24									    VARCHAR(MAX),
Account_older_adults_ages_25_plus								    VARCHAR(MAX),
Account_primary_education_or_less_ages_15_plus 						VARCHAR(MAX),
Account_secondary_education_or_more_ages_15_plus 					VARCHAR(MAX),
Account_income_poorest_40_percent_ages_15_plus						VARCHAR(MAX),
Account_income_richest_60_ages_15_plus 								VARCHAR(MAX),
Account_rural_age_15_plus 											VARCHAR(MAX),
Financial_institution_account_age_15_plus 							VARCHAR(MAX),
Financial_institution_account_male_age_15_plus 						VARCHAR(MAX),
Financial_institution_account_in_labor_force_age_15_plus 			VARCHAR(MAX),
Financial_institution_account_out_of_labor_force_age_15_plus 		VARCHAR(MAX),
Financial_institution_account_female_age_15_plus 					VARCHAR(MAX),
Financial_institution_account_young_adults_age_15_24 				VARCHAR(MAX),
Financial_institution_account_older_adults_age_25_plus 				VARCHAR(MAX),
Financial institution account_primary_education_or_less_age_15_plus VARCHAR(MAX),	
Financial_institution_account_seconday_education_or_more_age_15_plus VARCHAR(MAX),
Financial_institution_account_income_poorest_40_percent_age_15_plus  VARCHAR(MAX),	
Financial_institution_account_income_richest_60_age_15_plus 		VARCHAR(MAX),
Financial_institution_account_rural_age_15_plus 					VARCHAR(MAX),
Withdrawal_in_the_past_year_with_a_financial_institution_account_age_15_plus	VARCHAR(MAX),
No_account_because_financial_institutions_are_too_far_away_age_15_plus 			VARCHAR(MAX),
No_account_because_financial_institutions_are_too_far_away_without_a_financial_institution_account_age_15_plus 	VARCHAR(MAX), 	
No_account_because_financial_services_are_too_expensive_age_15_plus 											VARCHAR(MAX),
No_account_because_financial_services_are_too_expensive_without_a_financial_institution_account_age_15_plus 	VARCHAR(MAX),
No_account_because_of_lack_of_necessary_documentation_age_15_plus 												VARCHAR(MAX),
No_account_because_of_lack_of_necessary_documentation_without_a_financial_institution_account_age_15_plus 		VARCHAR(MAX),
No_account_because_of_lack_of_trust_in_financial_institutions_age_15_plus 										VARCHAR(MAX),
No_account_because_of_lack_of_trust_in_financial_institutions_without_a_financial_institution_account_age_15_plus 	VARCHAR(MAX),
No_account_because_of_religious_reasons_age_15_plus 																VARCHAR(MAX),
No_account_because_of_religious_reasons_without_a_financial_institution_account_age_15_plus 						VARCHAR(MAX),
No_account_because_of_insufficient_funds_age_15_plus 																VARCHAR(MAX),
No_account_because_of_insufficient_funds_without_a_financial_institution_account_age_15_plus 						VARCHAR(MAX),
No_account_because_someone_in_the_family_has_an_account_age_15_plus 												VARCHAR(MAX),
No_account_because_someone_in_the_family_has_an_account_without_a_financial_institution_account_age_15_plus 		VARCHAR(MAX),
No_account_because_of_no_need_for_financial_services_ONLY_age_15_plus 												VARCHAR(MAX),
No_account_because_of_no_need_for_financial_services_ONLY_without_a_financial_institution_account_age_15_plus 		VARCHAR(MAX),
Main_mode_of_withdrawal_ATM_percentage_with_a_financial_institution_account_age_15_plus 							VARCHAR(MAX),
Main_mode_of_withdrawal_bank_teller_percentage_with_a_financial_institution_account_age_15_plus 					VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_age_15_plus															VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_male_age_15_plus													VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_in_labor_force_age_15_plus											VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_out_of_labor_force_age_15_plus										VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_female_age_15_plus													VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_young_adults_age_15_24												VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_older_adults_age_25_plus											VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_primary_education_or_less_age_15_plua								VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_secondary_education_or_more_age_15_plus								VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_income_poorest_40_percent_age_15_plus								VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_income_richest_60_percent_age_15_plus								VARCHAR(MAX),
Used_the_internet_to_pay_bills_in_the_past_year_rural_age_15_plus													VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_age_15_plus								VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_male_age_15_plus							VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_in_labor_force_age_15_plus				VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_out_of_labor_force_age_15_plus			VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_female_age_15_plus						VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_youn_adults_age_15_24					VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_older_adults_age_25_plus					VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_primary_education_or_less_age_15_plus	VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_secondary_education_or_less_age_15_plus	VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_income_poorest_40_percent_age15_plus		VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_income_richest_60_percent_age_15_plus	VARCHAR(MAX),
Used_the_internet_to_pay_bills_or_to_buy_something_online_in_the_past_year_rural_age_15_plus						VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_age_15_plus												VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_male_age 15_plus											VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_in_labor_force_age_15_plus								VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_out_of_labor_force_age_15_plus							VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_female_age_15_plus										VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_young_adults_age_15_24									VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_older_adults_age_25_plus									VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_primary_education_or_less_age_15_plus					VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_secondary_education_or_more_age_15_plus					VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_income_poorest_40_percent_age_15_plus					VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_income_richest_60_percent_age_15_plus					VARCHAR(MAX),
Used_the_internet_to_buy_something_online_in_the_past_year_rural_age_15_plus										VARCHAR(MAX),
Paid_online_for_internet_purchase_internet_purchasers_age_15_plus													VARCHAR(MAX),
Paid_cash_on_delivery_for_internet_purchase_internet_purchasers_age_15_plus											VARCHAR(MAX),
Saved_to_start_operat_or_expand_a_farm_or_business_age_15_plus 														VARCHAR(MAX),
Saved_to_start_operat_or_expand_a_farm_or_business_male_age_15_plus 												VARCHAR(MAX),
Saved_to_start_operat_or_expand_a_farm_or_business_in_labor_force_age_15_plus 										VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_busines_out_of_labor_force_age_15_plus 									VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_female_age_15_plus 												VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_young_adults_age_15_24 											VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_older_adults_age_25_plus 										VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_primary_education_or_less_age_15_plus 							VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_secondary_education_or_less_age_15_plus 						VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_income_poorest_40_percent_age_15_plus 							VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_income_richest_60_percent_age_15_plus 							VARCHAR(MAX),
Saved_to_start_operate_or_expand_a_farm_or_business_rural_age_15_plus 												VARCHAR(MAX),
Saved_for_old_age_age_15_plus 																						VARCHAR(MAX),
Saved_for_old_age_male_age_15_plus 																					VARCHAR(MAX),
Saved_for_old_age_in_labor_force_age_15_plus 																		VARCHAR(MAX),
Saved_for_old_age_out_of_labor_force_age_15_plus 																	VARCHAR(MAX),
Saved_for_old_age_female_age_15_plus 																				VARCHAR(MAX),
Saved_for_old_age_young_adults_age_15_24 																			VARCHAR(MAX),
Saved_for_old_age_older_adults_age_25_plus 																			VARCHAR(MAX),
Saved_for_old_age_primary_education_or_less_age_15_plus 															VARCHAR(MAX),
Saved_for_old_age_secondary_education_or_more_age_15_plus 															VARCHAR(MAX),
Saved_for_old_age_income_poorest_40_percent_age_15_plus 															VARCHAR(MAX),
Saved_for_old_age_income_richest_60_percent_age_15_plus 															VARCHAR(MAX),
Saved_for_old_age_rural_age_15_plus 																				VARCHAR(MAX),
Saved_at_a_financial_institution_age_15_plus 																		VARCHAR(MAX),
Saved_at_a_financial_institution_male_age_15_plus 																	VARCHAR(MAX),
Saved_at_a_financial_institution_in_labor_force_age_15_plus 														VARCHAR(MAX),
Saved_at_a_financial_institution_out_of_labor_force_age_15_plus 													VARCHAR(MAX),
Saved_at_a_financial_institution_female_age_15_plus 																VARCHAR(MAX),
Saved_at_a_financial_institution_young_adults_age_15_24) 															VARCHAR(MAX),
Saved_at_a_financial_institution_older_adults_age_25_plus 															VARCHAR(MAX),
Saved_at_a_financial_institution_primary_education_or_less_age_15_plus 												VARCHAR(MAX),
Saved_at_a_financial_institution_secondary_education_or_more_age_15_plus 											VARCHAR(MAX),
Saved_at_a_financial_institution_income_poorest_40_percent_age_15_plus 												VARCHAR(MAX),
Saved_at_a_financial_institution_income_richest_60_plus_age_15_plus 												VARCHAR(MAX),
Saved_at_a_financial_institution_rural_age_15_plus 																	VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_age_15_plus 												VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_male_age_15_plus 											VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_in_labor_force_age_15_plus 								VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_out_of_labor_force_age_15_plus 							VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_female_age_15_plus 										VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_young_adults_age_15_24 									VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_older_adults_age_25_plus 									VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_primary_education_or_less_age_15_plus 					VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_secondary_education_or_more_age_15_plus 					VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_income_poorest_40_percentage_age_15_plus 					VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_income_richest_60_percent_age_15_plus 					VARCHAR(MAX),
Saved_using_a_savings_club_or_a_person_outside_the_family_rural_age_15_plus 										VARCHAR(MAX),
Saved_for_education_or_school_fees_age_15_plus 																		VARCHAR(MAX),
Saved_for_education_or_school_fees_male_age_15_plus 																VARCHAR(MAX),
Saved_for_education_or_school_fees_in_labor_force_age_15_plus 														VARCHAR(MAX),
Saved_for_education_or_school_fees_out_of_labor_force_age_15_plus 													VARCHAR(MAX),
Saved_for_education_or_school_fees_female_age_15_plus 																VARCHAR(MAX),
Saved_for_education_or_school_fees_young_adults_age_15_24 															VARCHAR(MAX),
Saved_for_education_or_school_fees_older_adults_age_25_plus 														VARCHAR(MAX),
Saved_for_education_or_school_fees_primary_education_or_less_age_15_plus 											VARCHAR(MAX),
Saved_for_education_or_school_fees_secondary_education_or_more_age_15_plus 											VARCHAR(MAX),
Saved_for_education_or_school_fees_income_poorest_40_percent_age_15_plus 											VARCHAR(MAX),
Saved_for_education_or_school_fees_income_richest_60_percent_age_15_plus 											VARCHAR(MAX),
Saved_for_education_or_school_fees_rural_age_15_plus 																VARCHAR(MAX),
Saved_any_money_in_the_past_year_age_15_plus 																		VARCHAR(MAX),
Saved_any_money_in_the_past_year_male_age_15_plus 																	VARCHAR(MAX),
Saved_any_money_in_the_past_year_in_labor_force_age_15_plus 														VARCHAR(MAX),
Saved_any_money_in_the_past_year_out_of_labor_force_age_15_plus 													VARCHAR(MAX),
Saved_any_money_in_the_past_year_female_age_15_plus 																VARCHAR(MAX),
Saved_any_money_in_the_past_year_young_adults_age_15_24 															VARCHAR(MAX),
Saved_any_money_in_the_past_year_older_adults_age_25_plus 															VARCHAR(MAX),
Saved_any_money_in_the_past_year_primary_education_or_less_age_15_plus 												VARCHAR(MAX),
Saved_any_money_in_the_past_year_secondary_education_or_more_age_15_plus 											VARCHAR(MAX),
Saved_any_money_in_the_past_year_income_poorest_40_percent_age_15_plus 												VARCHAR(MAX),
Saved_any_money_in_the_past_year_income_richest_60_percent_age_15_plus 												VARCHAR(MAX),
Saved_any_money_in_the_past_year_rural_age_15_plus 																	VARCHAR(MAX),
Outstanding_housing_loan_age_15_plus 																				VARCHAR(MAX),
Outstanding_housing_loan_male_age_15_plus 																			VARCHAR(MAX),
Outstanding_housing_loan_in_labor_force_age_15_plus 																VARCHAR(MAX),
Outstanding_housing_loan_out_of_labor_force_age_15_plus 															VARCHAR(MAX),
Outstanding_housing_loan_female_age_15_plus 																		VARCHAR(MAX),
Outstanding_housing_loan_young_adults_age_15_24 																	VARCHAR(MAX),
Outstanding_housing_loan_older_adults_age_25_plus 																	VARCHAR(MAX),
Outstanding_housing_loan_primary_education_or_less_age_15_plus 														VARCHAR(MAX),
Outstanding_housing_loan_secondary_education_or_more_age_15_plus 													VARCHAR(MAX),
Outstanding_housing_loan_income_poorest_40_percent_age_15_plus 														VARCHAR(MAX),
Outstanding_housing_loan_income_richest_60_percent_age_15_plus 														VARCHAR(MAX),
Outstanding_housing_loan_rural_age_15_plus 																			VARCHAR(MAX),
Debit_card_ownership_age_15_plus 																					VARCHAR(MAX),
Debit_card_ownership_male_age_15_plus 																				VARCHAR(MAX),
Debit_card_ownership_in_labor_force_age_15_plus 																	VARCHAR(MAX),
Debit_card_ownership_out_of_labor_force_age_15_plus 																VARCHAR(MAX),
Debit_card_ownership_female_age_15_plus 																			VARCHAR(MAX),
Debit_card_ownership_young_adults_age_15_24 																		VARCHAR(MAX),
Debit_card_ownership_older_adults_age_25_plus 																		VARCHAR(MAX),
Debit_card_ownership_primary_education_or_less_age_15_plus 															VARCHAR(MAX),
Debit_card_ownership_secondary_education_or_more_age_15_plus 														VARCHAR(MAX),
Debit_card_ownership_income_poorest_40_percent_age_15_plus 															VARCHAR(MAX),
Debit_card_ownership_income_richest_60_percent_age_15_plus 															VARCHAR(MAX),
Debit_card_ownership_rural_age_15_plus 																				VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_age_15_plus 																VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_male_age_15_plus 															VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_in_labor_force_age_15_plus 													VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_out_of_labor_force_age_15_plus 												VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_female_age_15_plus 															VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_young_adults_age_15_24 														VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_older_adults_age_25_plus 													VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_primary_education_or_less_age_15_plus 										VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_secondary_education_or_more_age_15_plus 									VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_income_poorest_40_percent_age_15_plus 										VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_income_richest_60_percent_age_15_plus 										VARCHAR(MAX),
Borrowed_for_health_or_medical_purposes_rural_age_15_plus 															VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_age_15_plus 													VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_male_age_15_plus 											VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_in_labor_force_age_15_plus 									VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_out_of_labor_force_age_15_plus 								VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_female_age_15_plus											VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_young_adults_age_15_24 										VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_older_adults_age_25_plus 									VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_primary_education_or_less_age_15_plus 						VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_secondary_education_or_more_age_15_plus 						VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_income_poorest_40_percent_age_15_plus 						VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_income_richest_60_plus_age_15_plus 							VARCHAR(MAX),
Borrowed_to_start_operate_or_expand_a_farm_or_business_rural_age_15_plus 											VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_age_15_plus 																VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_male_age_15_plus 															VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_in_labor_force_age_15_plus 												VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_out_of_labor_force_age_15_plus 											VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_female_age_15_plus 														VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_young_adults_age_15_24 													VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_older_adults_age_25_plus 													VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_primary_education_or_less_age_15_plus 									VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_secondary_education_or_more_age_15_plus 									VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_income_poorest_40_percent_age_15_plus 									VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_income_richest_60_percent_age_15_plus 									VARCHAR(MAX),
Borrowed_from_a_store_by_buying_on_credit_rural_age_15_plus 														VARCHAR(MAX),
Borrowed_for_education_or_school_fees_age_15_plus 																	VARCHAR(MAX),
Borrowed_for_education_or_school_fees_male_age_15_plus 																VARCHAR(MAX),
Borrowed_for_education_or_school_fees_in_labor_force_age_15_plus 													VARCHAR(MAX),
Borrowed_for_education_or_school_fees_out_of_labor_force_age_15_plus 												VARCHAR(MAX),
Borrowed_for_education_or_school_fees_female_age_15_plus 															VARCHAR(MAX),
Borrowed_for_education_or_school_fees_young_adults_age_15_24 														VARCHAR(MAX),
Borrowed_for_education_or_school_fees_older_adults_age_25_plus 														VARCHAR(MAX),
Borrowed_for_education_or_school_fees_primary_education_or_less_age_15_plus 										VARCHAR(MAX),
Borrowed_for_education_or_school_fees_secondary_education_or_more_age_15_plus 										VARCHAR(MAX),
Borrowed_for_education_or_school_fees_income_poorest_40_percent_age_15_plus 										VARCHAR(MAX),
Borrowed_for_education_or_school_fees_income_richest_60_plus_age_15_plus 											VARCHAR(MAX),
Borrowed_for_education_or_school_fees_rural_age_15_plus 															VARCHAR(MAX),
Borrowed_from_a_financial_institution_age_15_plus 																	VARCHAR(MAX),
Borrowed_from_a_financial_institution_male_age_15_plus 																VARCHAR(MAX),
Borrowed_from_a_financial_institution_in_labor_force_age_15_plus 													VARCHAR(MAX),
Borrowed_from_a_financial_institution_out_of_labor_force_age_15_plus 												VARCHAR(MAX),
Borrowed_from_a_financial_institution_female_age_15_plus 															VARCHAR(MAX),
Borrowed_from_a_financial_institution_young_adults_age_15_24 														VARCHAR(MAX),
Borrowed_from_a_financial_institution_older_adults_age_25_plus 														VARCHAR(MAX),
Borrowed_from_a_financial_institution_primary_education_or_less_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_secondary_education_or_more_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_income_poorest_40_percent_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_income_richest_60_percent_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_rural_age_15_plus 															VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_age_15_plus 											VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_male_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_in_labor_force_age_15_plus 								VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_out_of_labor_force_age_15_plus 							VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_female_age_15_plus 										VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_young_adults_age_15_24 									VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_older_adults_age_25_plus 								VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_primary_education_or_less_age_15_plus 					VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_secondary_education_or_more_age_15_plus 				VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_income_poorest_40_percent_age_15_plus 					VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_income_richest_60_percent_age_15_plus 					VARCHAR(MAX),
Borrowed_from_a_financial_institution_or_used_a_credit_card_rural_age_15_plus 										VARCHAR(MAX),
Borrowed_from_family_or_friends_age_15_plus 																		VARCHAR(MAX)
);
"""

INSERT_INTO_MERCHANTS_TABLE_SQL = """
INSERT INTO merchants (merchant_name, cash_in_count, cash_out_count, payment_count, distinct_customers_count) 
SELECT distinct st.recepient_name, 
	sum(case when st.transaction_type = 'CASH-IN' then st.transaction_amount else 0 end),
	sum(case when st.transaction_type = 'CASH-OUT' then st.transaction_amount else 0 end), 
	sum(case when st.transaction_type = 'PAYMENT' then st.transaction_amount else 0 end),
	count(distinct st.originator_name)
FROM staging_transactions st
WHERE st.recepient_name like 'M%'
GROUP BY st.recepient_name, st.originator_name;
"""

INSERT_INTO_CUSTOMERS_TABLE_SQL = """
INSERT INTO customers (customer_name, cash_in_count, cash_out_count, payment_count, transfer_count, first_transaction_step_time , last_transaction_step_time, distinct_top_transfer_to_customer_count, distinct_merchant_count) 
SELECT distinct st.recepient_name, 
	sum(case when st.transaction_type = 'CASH-IN' then st.transaction_amount else 0 end),
	sum(case when st.transaction_type = 'CASH-OUT' then st.transaction_amount else 0 end), 
	sum(case when st.transaction_type = 'PAYMENT' then st.transaction_amount else 0 end),
	sum(case when st.transaction_type = 'TRANSFER' then st.transaction_amount else 0 end),
	min(st.step) as min_step_time,
	max(st.step) as max_step_time,
	count(case when st.transaction_type = 'TRANSFER' then st.recepient_name else '' end),
	count(case when st.recepient_name like 'M%' then st.recepient_name else '' end)
FROM staging_transactions st
GROUP BY st.recepient_name, st.originator_name;
"""